name: Build and Dockerize React Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Client
        run: npm install

      - name: Build React app
        working-directory: ./Client
        run: npm run build

      - name: Build Docker image
        working-directory: ./Client
        run: docker build -t petadoption-frontend .

      # Optional: Push Docker image to Docker Hub or GitHub Container Registry
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   run: docker push <your-dockerhub-username>/petadoption-frontend:latest