name: Build and Dockerize React Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Client
        run: npm install

      - name: Build React app
        working-directory: ./Client
        run: npm run build

      - name: Build Docker image
        working-directory: ./Client
        run: docker build -t petadoption-frontend .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ~/PetAdoptionSite &&
            git pull &&
            docker stop petadoption-frontend-container || true &&
            docker rm petadoption-frontend-container || true &&
            docker build -t petadoption-frontend ./Client &&
            docker run -d -p 80:3000 --name petadoption-frontend-container petadoption-frontend
          "